"use client";
import React from "react";

const sampleLogs = [
  { id: 1, user: "Bro Segun", action: "CREATE", table: "income_transactions", description: "Added Sunday Collection - ₦94,700", date: "05 Jan 2026, 10:15 AM" },
  { id: 2, user: "Super Admin", action: "APPROVE", table: "income_transactions", description: "Approved Sunday Collection - Jan 5", date: "05 Jan 2026, 02:30 PM" },
  { id: 3, user: "Finance Officer", action: "CREATE", table: "expense_transactions", description: "Added Cleaning expense - ₦7,900", date: "05 Jan 2026, 03:00 PM" },
  { id: 4, user: "Treasurer", action: "APPROVE", table: "expense_transactions", description: "Approved Cleaning expense", date: "05 Jan 2026, 04:15 PM" },
  { id: 5, user: "Bro Segun", action: "CREATE", table: "income_transactions", description: "Added Sunday Collection - ₦172,310", date: "12 Jan 2026, 10:30 AM" },
  { id: 6, user: "Super Admin", action: "UPDATE", table: "profiles", description: "Updated user role for Finance Officer", date: "15 Jan 2026, 09:00 AM" },
];

const actionColors: Record<string, string> = {
  CREATE: "bg-emerald-100 text-emerald-800",
  UPDATE: "bg-blue-100 text-blue-800",
  DELETE: "bg-red-100 text-red-800",
  APPROVE: "bg-amber-100 text-amber-800",
  REJECT: "bg-red-100 text-red-800",
};

export default function AuditLogsPage() {
  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl md:text-3xl font-bold text-slate-900 mb-1">Audit Logs</h1>
        <p className="text-slate-500 text-sm">Read-only record of all system activities. These logs cannot be modified.</p>
      </div>

      <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-6 flex items-center gap-3">
        <svg className="w-5 h-5 text-blue-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        <p className="text-sm text-blue-800">Audit logs are <strong>read-only</strong> and automatically generated by the system. No user can edit or delete these records.</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
          <h3 className="text-base font-bold text-slate-800">Recent Activity</h3>
        </div>
        <div className="divide-y divide-slate-100">
          {sampleLogs.map(log => (
            <div key={log.id} className="px-4 md:px-6 py-4 flex flex-col sm:flex-row sm:items-center gap-2">
              <div className="flex items-center gap-3 flex-1">
                <div className="w-8 h-8 rounded-full bg-slate-200 flex items-center justify-center text-xs font-bold text-slate-600 shrink-0">{log.user[0]}</div>
                <div>
                  <p className="text-sm text-slate-900"><strong>{log.user}</strong> <span className="text-slate-400">·</span> <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${actionColors[log.action] || "bg-slate-100 text-slate-800"}`}>{log.action}</span></p>
                  <p className="text-sm text-slate-500 mt-0.5">{log.description}</p>
                </div>
              </div>
              <div className="text-xs text-slate-400 whitespace-nowrap sm:text-right">{log.date}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
